trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    # Install NodeJS
    curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
    sudo apt-get install -y nodejs

    # Install Newman and reporter
    sudo npm install -g newman
    sudo npm install -g newman-reporter-htmlextra

    # Run Newman and generate the report
    newman run "TestCollection.postman_collection9.json" -e "TestEnvironment.postman_environment.json" -r htmlextra --reporter-htmlextra-export report.html
  displayName: 'Run Newman and generate report'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: report.html
    artifact: 'NewmanReports'
  displayName: 'Publish Newman report as an artifact'
