# This is a basic workflow to help you get started with Actions

name: Newman CLI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

# Steps represent a sequence of tasks that will be executed as part of the job
steps:
  # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  - uses: actions/checkout@v3
  - name: created
    run: |
      pair SampleArtifact
       
      # Install NodeJS
      - name: Install Node
        uses: actions/checkout@v3
        with:
           node-version: '18.x'
           
      # Install Newman and reporter
      - name: Install Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
          
       # Run Collection  
      - name: Run Collection
        run: |
          Newman run "BABE-IMP Automation.postman_collection.json" -e "BABE Environment.postman_environment.json"
      
      # Generate Report
      - name: Generate Report
        run: |
         Newman run "BABE-IMP Automation.postman_collection.json" -e "BABE Environment.postman_environment.json" -d IMP_TestData.csv  -r htmlextra --reporter-htmlextra-export SampleArtifacts/report.html

      # Publish the Report
      - name: Publish Report
       uses: actions/upload-artifact@v2
       with:
          name: Reports
          path: SampleArtifacts
          
          
