trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g newman
    npm install -g newman-reporter-htmlextra
  displayName: 'Install Newman and HTMLExtra Reporter'

- script: |
newman run "TestCollection.postman_collection1.json" -e "MasterAPI ENV.postman_environment1.json" -r htmlextra --reporter-htmlextra-export SampleArtifacts/report.html 

displayName: 'Run Newman Collection and Generate Report'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'SampleArtifacts'
    ArtifactName: 'Reports'
  displayName: 'Publish Report Artifact'
