name: Newman CLI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: createdir
        run: |
          mkdir SampleArtifact

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run Collection
        run: |
          newman run "TestCollection.postman_collection1.json" -e "MasterAPI ENV.postman_environment1.json"

      - name: Generate Report
        run: |
          newman run "TestCollection.postman_collection1.json" -e "MasterAPI ENV.postman_environment1.json" -r htmlextra --reporter-htmlextra-export SampleArtifacts/report.html

      - name: Publish Report
        uses: actions/upload-artifact@v2
        with:
          name: Reports
          path: SampleArtifacts
